### ISSUE TITLE
@astro-community/astro-embed-vimeo package doesn't list the dependency of @astro-community/astro-embed-utils

### ISSUE THREAD

**Issue by KristianH** [delucis/astro-embed#112]
The astro embed Vimeo package has a dependency to astro-embed-utils.

The dependency is imported in [packages/astro-embed-vimeo/Vimeo.astro](https://github.com/delucis/astro-embed/blob/main/packages/astro-embed-vimeo/Vimeo.astro#L2)
```astro
---
import { safeGet } from '@astro-community/astro-embed-utils';
import urlMatcher from './matcher';
```

The dependency is missing in the [package.json](https://github.com/delucis/astro-embed/blob/main/packages/astro-embed-vimeo/package.json). 

Similar to this the `astro-embed-link-preview` ([package.json](https://github.com/delucis/astro-embed/blob/main/packages/astro-embed-link-preview/package.json#L32-L34)) or astro-embed-twitter ([package.json](https://github.com/delucis/astro-embed/blob/main/packages/astro-embed-twitter/package.json#L33-L35)) has this dependency declared.

```json
  "dependencies": {
    "@astro-community/astro-embed-utils": "^0.1.1"
  }
```

Note: maybe the version should also set to `"^0.1.2"`

**Comment by delucis** [comment]
Good catch! Yes, we should add this to the dependencies.

This is the second time in a week or so that this has happened to different packages. I’m wondering if we should switch to a pnpm monorepo instead as that should error in cases like this instead of how the npm monorepo keeps working locally.
