### ISSUE TITLE
Lighthouse: Links are not crawlable with `<YouTube>`

### ISSUE THREAD

**Issue by jrouleau** [delucis/astro-embed#116]
Introduced by https://github.com/delucis/astro-embed/pull/102

The play button is now an `<a>` elements  that has its `href` attribute removed thereby creating the following issues with Lighthouse scores:

### Links are not crawlable
Search engines may use href attributes on links to crawl websites. Ensure that the `href` attribute of anchor elements links to an appropriate destination, so more pages of the site can be discovered. [Learn how to make links crawlable](https://support.google.com/webmasters/answer/9112205)

**Comment by delucis** [comment]
Thanks for the issue! I noticed this as an accessibility problem too: links without `href` are not focusable, so the play button can’t be reached with the keyboard.

I think this will need fixing in https://github.com/paulirish/lite-youtube-embed which we depend on — maybe by replacing the link with a button when present.

**Comment by delucis** [comment]
Update: have a fix on a local branch. Will open an upstream PR tomorrow.

**Comment by delucis** [comment]
Opened a PR here: https://github.com/paulirish/lite-youtube-embed/pull/177

Let’s see if we get a response and if not we can look to revert the progressive enhancement pattern in `astro-embed` or use my fork of `lite-youtube-embed`.

**Comment by jasikpark** [comment]
Potentially off-topic, but it'd be great if the youtube component survived RSS webpage content feed reader sanitization.

<img width="663" alt="image" src="https://github.com/delucis/astro-embed/assets/10626596/e7f35198-02b8-4329-936d-7483844752a2">
v.s.

<img width="814" alt="image" src="https://github.com/delucis/astro-embed/assets/10626596/eac62b38-68bc-4e4d-a990-2730fceda144">

**Comment by delucis** [comment]
@jasikpark I think that’s unrelated — see #59 

Depends a bit how you’re rendering the RSS feed I suspect.

**Comment by ARkrOSClou** [comment]
hey, any progress here?
[pagespeed](https://pagespeed.web.dev/analysis/https-astro-embed-netlify-app-components-youtube/pvo6kix9lz?form_factor=desktop)
![image](https://github.com/user-attachments/assets/7eb0074a-0101-4fd2-9a38-401bad8b2a0d)

**Comment by ARkrOSClou** [comment]
hey, any progress here?
[pagespeed](https://pagespeed.web.dev/analysis/https-astro-embed-netlify-app-components-youtube/pvo6kix9lz?form_factor=desktop)
![image](https://github.com/user-attachments/assets/7eb0074a-0101-4fd2-9a38-401bad8b2a0d)

**Comment by jasikpark** [comment]
> @jasikpark I think that’s unrelated — see #59
> 
> Depends a bit how you’re rendering the RSS feed I suspect.

For me, this is the https://feedbin.com service ingesting the regular html of the webpage, since I don't render my RSS with content included, since I use Markdoc and need to sort out how to use the Container API with that still

**Comment by LeFede** [comment]
> hey, any progress here? [pagespeed](https://pagespeed.web.dev/analysis/https-astro-embed-netlify-app-components-youtube/pvo6kix9lz?form_factor=desktop) ![image](https://private-user-images.githubusercontent.com/46116126/348598757-7eb0074a-0101-4fd2-9a38-401bad8b2a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzODg0MjQsIm5iZiI6MTcyMjM4ODEyNCwicGF0aCI6Ii80NjExNjEyNi8zNDg1OTg3NTctN2ViMDA3NGEtMDEwMS00ZmQyLTlhMzgtNDAxYmFkOGIyYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAxMDg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNzUwYmVmOGRiMjZmZGNlOTg1YmU2OWUyMzg0ZGRiODc3ODk3MzgyNGU4OWYwZGQ2ZmYwODYxOWY3NDliYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uVSgEJczqaUZ4rpoAQkuUGAhr5fJpCTspUXSqOhdAfU)

x2 here! waiting for the fix

**Comment by delucis** [comment]
Fixed in the latest release of `@astro-community/astro-embed-youtube` — [v0.5.3](https://github.com/delucis/astro-embed/releases/tag/%40astro-community%2Fastro-embed-youtube%400.5.3).
