### ISSUE TITLE
Feature Request: disable images via a prop

### ISSUE THREAD

**Issue by jasikpark** [delucis/astro-embed#129]
It'd be nice to be able to not render images for an open graph link when you want something that's less large / if the open graph image is not of high value.

Ex:

<img width="717" alt="image" src="https://github.com/delucis/astro-embed/assets/10626596/0ac41568-ea7c-4493-b5a9-4975d95ab449">

v.s.

<img width="565" alt="image" src="https://github.com/delucis/astro-embed/assets/10626596/125a5453-0d9a-4517-bfd3-5bbae62f6662">

**Comment by delucis** [comment]
Seems like a reasonable request if you’d like to PR?

Other option is to hide the image with CSS, but obviously just skipping it in the component output would be ideal, so wouldn’t mind adding this 👍
