### ISSUE TITLE
Invalid video ID raises exception with Vimeo provider

### ISSUE THREAD

**Issue by sylvinus** [delucis/astro-embed#135]
The YT embed is resistant to invalid video IDs, but the Vimeo one fails with `Cannot read properties of undefined (reading 'endsWith')`.

This is an issue because someone unpublishing a video can break our builds ...

https://github.com/delucis/astro-embed/blob/96ce82eef9ccbcf228ad2e589d066974899e805f/packages/astro-embed-vimeo/Vimeo.astro#L43

Thanks!

**Comment by delucis** [comment]
Thanks for the issue @sylvinus! Would be happy to look at a PR to make handling that case more robust.
