### ISSUE TITLE
Support Open Graph embeds

### ISSUE THREAD

**Issue by fflaten** [delucis/astro-embed#30]
Maybe include a generic embed that consumes Open Graph/`og` meta-tags similar to how Discord, Twitter etc. do it?

Would be a nice feature to highlight specific links in your content.

**Comment by delucis** [comment]
Nice idea! I guess this would kind of be like a "link preview" component.

**Comment by fflaten** [comment]
👍  Wasn't sure if it belonged here though since it's not interactive, but it's often called embed so hopefully intuitive for users.

**Comment by delucis** [comment]
Added in #73 and available in `@astro-community/astro-embed-link-preview` and in v0.7 of `astro-embed`.

Thanks to @vasfvitor for contributing this!
