### ISSUE TITLE
MDX support for integration-package?

### ISSUE THREAD

**Issue by fflaten** [delucis/astro-embed#34]
With Astro Flavored Markdown (AFM) deprecated and removed in Astro v2 in favor of MDX, what's the future for the remark plugin?

Can we support MDX to keep the easy URL-based auto import working? Or provide instructions for how to do it?

**Comment by delucis** [comment]
Yeah, for v2 we can probably drop support for AFMD here too and only support MDX. Injecting components to MDX is a little more complex. We can use https://github.com/delucis/astro-auto-import for the import injection and borrow from the Astro docs on how to create the component node: https://github.com/withastro/docs/blob/8429df5d014e485d1bc90fcde19621263aa85099/integrations/utils/makeComponentNode.ts#L19-L33

**Comment by delucis** [comment]
Implemented in #44!
