### ISSUE TITLE
Astro Embed Not Working with Astro v3.0

### ISSUE THREAD

**Issue by jawills** [delucis/astro-embed#57]
The astro embed does not render on the browser for YouTube components. The <lite-youtube/> component is inserted in the dom correctly, but no content appears.

This is for both URL embeds and <YouTube id="" /> components.

Versions:
    "astro": "^3.0.2",
    "astro-embed": "^0.5.1",

Production Instance:
https://www.1sync.co/build-salesforce-deployment-pipeline-with-github-actions
(At the bottom, search "YouTube")

**Comment by delucis** [comment]
Thanks for the issue @jawills. Looks like the CSS and script are missing for some reason 🤔 

Any chance you can reproduce the issue or share your code so I can see how the component is used etc?

**Comment by jawills** [comment]
I was able to recreate the bug with the source code. This is copied from the astro-wind template.

Source code: https://github.com/jawills/youtube-embed-debug
Live Site: https://youtube-embed-debug.vercel.app/astrowind-template-in-depth

**Comment by jawills** [comment]
Seems to be an issue with the astrowind template. I will close this for now and reopen if needed.

**Comment by jawills** [comment]
If someone looks at this in the future, it is a known issue with Astro. You can see the open issue here: https://github.com/withastro/astro/issues/7761

**Comment by delucis** [comment]
Thank you for sharing @jawills!
