### ISSUE TITLE
The player is over the thumbnail with YouTube

### ISSUE THREAD

**Issue by torn4dom4n** [delucis/astro-embed#71]
## Describe the Bug

I'm using `astro-embed` with Starlight. When I click to play video, the player will be over the thumbnail.

![image](https://github.com/delucis/astro-embed/assets/27698189/37ed3fcf-eaf9-46e0-83e5-393a530f6797)

## Link to Minimal Reproducible Example

https://github.com/AREA44/starlight-tailwind-template/tree/71b3e7a57568f8be1b871f07637e2585011a7f25

**Comment by SuperShinyEyes** [comment]
This issue has disappeared when I updated `astro-embed-youtube` to v0.4.4.
