### ISSUE TITLE
Fix: Astro v4 compatibility

### ISSUE THREAD

**Issue by barrenechea** [delucis/astro-embed#80]
Hi! I've just attempted to update my project to Astro v4 (just released) and peer deps from this module are not allowing me to do a clean install.

<img width="877" alt="Screenshot 2023-12-05 at 11 49 11" src="https://github.com/delucis/astro-embed/assets/11593618/0ac6f3e2-619c-403f-ac88-42eb56b8556c">

Any input would be appreciated!

**Comment by delucis** [comment]
Hi @barrenechea! Could you share your `package.json`? v0.4.3 of `@astro-community/astro-embed-youtube` should support Astro v4.

**Comment by barrenechea** [comment]
Hey @delucis ! Thank you for reaching out. It seems that it was an issue with either my `node_modules` folder or `package-lock.json`, I'm unable to replicate the message. Now it fails because of `astro-og-canvas` 🤣

Closing the issue, thank you very much!

**Comment by delucis** [comment]
Ah I think we didn’t update `astro-og-canvas` peer dependencies yet! We’ll get there eventually :-D
